drop policy "Enable read access for all users" on "public"."card_in_tower";

alter table "public"."card_in_tower" drop constraint "Card_in_deck_card_number_key";

alter table "public"."card_in_tower" drop constraint "Card_in_deck_pkey";

alter table "public"."card_in_board_deck" drop constraint "card_in_board_deck_pkey";

alter table "public"."card_in_board_discard_deck" drop constraint "card_in_board_discard_deck_pkey";

drop index if exists "public"."Card_in_deck_card_number_key";

drop index if exists "public"."Card_in_deck_pkey";

drop index if exists "public"."card_in_board_deck_pkey";

drop index if exists "public"."card_in_board_discard_deck_pkey";

alter table "public"."card_in_board_deck" drop column "id";

alter table "public"."card_in_board_deck" add column "card_number" smallint not null;

alter table "public"."card_in_board_discard_deck" drop column "id";

alter table "public"."card_in_tower" drop column "id";

alter table "public"."card_in_tower" alter column "card_number" add generated by default as identity;

CREATE UNIQUE INDEX card_in_tower_pkey ON public.card_in_tower USING btree (card_number);

CREATE UNIQUE INDEX card_in_board_deck_pkey ON public.card_in_board_deck USING btree (card_number);

CREATE UNIQUE INDEX card_in_board_discard_deck_pkey ON public.card_in_board_discard_deck USING btree (card_number);

alter table "public"."card_in_tower" add constraint "card_in_tower_pkey" PRIMARY KEY using index "card_in_tower_pkey";

alter table "public"."card_in_board_deck" add constraint "card_in_board_deck_pkey" PRIMARY KEY using index "card_in_board_deck_pkey";

alter table "public"."card_in_board_discard_deck" add constraint "card_in_board_discard_deck_pkey" PRIMARY KEY using index "card_in_board_discard_deck_pkey";

alter table "public"."card_in_board_deck" add constraint "card_in_board_deck_card_number_fkey" FOREIGN KEY (card_number) REFERENCES card_variant(number) not valid;

alter table "public"."card_in_board_deck" validate constraint "card_in_board_deck_card_number_fkey";


